### ISSUE TITLE
Breaking changes in v2.0.0?

### ISSUE THREAD

**Issue by oliverlloyd** [wix-incubator/mjml-react#62]
Hi there 👋 

Thanks for all the work on this repo, it's great! Can I just check if the [recent major version bump](https://github.com/wix-incubator/mjml-react/commit/7894e20e52db6340e8bad2cbb731f6a3f2430db4) to `2.0.0` has any breaking changes in that we need to be aware of? I can't see any issues but just wanted to be certain.

Thanks

**Comment by LB22** [comment]
Well I seem to be getting this one but I'm not sure if it's because of this version or not

```
TypeError: _interopRequireDefault is not a function
    at Object.<anonymous> (C:\Users\LB\Documents\Programming\WebApps\myapp\node_modules\mjml-core\lib\index.js:66:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\LB\Documents\Programming\WebApps\myapp\node_modules\mjml\lib\index.js:12:41)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    ```

**Comment by oliverlloyd** [comment]
As per https://github.com/guardian/gateway/pull/706 & https://github.com/mjmlio/mjml/issues/2299#issuecomment-864526891 and @LB22 's comment, this is related to `@bable/runtime`

**Comment by daliusd** [comment]
I think there is nothing breaking in here. I remember alternative mjml rendering option was added but nothing else serious. Alternetive mjml rendering shouldn't affect anyone.
